### ISSUE TITLE
Removing UNK words from sentence ? why ?

### ISSUE THREAD

**Issue by kamalkraj** [facebookresearch/DME#4]
@kahne 
https://github.com/facebookresearch/DME/blob/a3217eedb69ceb15a472f6ccebc048b4a1cdc005/train.py#L67

why filtering out the words based on the combined embedding vocabulary in the preprocessing function ? instead of replacing with `<unk>` ?

For exapmle :

`sentence` : `hide new secretions from the parental units` 

if the word `secretions` is not in the emb_vocab ,
the sentence will be converted into `hide new from the parental units` , 
I think correct sentence should be `hide new <unk> from the parental units`

**Comment by kahne** [comment]
@kamalkraj 

We actually care about the semantics of whole sentences, so missing some words may not matter much. Moreover, we find that the `<unk>` placeholders almost have no contributions to encoding the OOV word semantics. So we just removed those OOV tokens and this also saves computation (because sentences are shorten a bit).

**Comment by douwekiela** [comment]
Worth mentioning, btw, that we do the same in InferSent: https://github.com/facebookresearch/InferSent/blob/master/train_nli.py#L86
